services:
  - type: web
    name: sistema-espetinho
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application --bind 10.0.0.105:$PORT --workers 2 --threads 4
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: 0
      - key: HOST
        value: 10.0.0.105
      - key: PORT
        value: 5000
      - key: SERVER_NAME
        value: 10.0.0.105:5000 