name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -c "import app; print('App imports successfully')"
    
    - name: Create deployment package
      run: |
        mkdir -p dist
        cp -r templates dist/
        cp -r static dist/
        cp app.py dist/
        cp requirements.txt dist/
        cp README.md dist/
        cp README_CAMERA.md dist/
        cp iniciar_com_camera.py dist/
        cp gerar_certificados.py dist/
        cp Caddyfile dist/
        cp wsgi.py dist/
        cp Procfile dist/
        cp runtime.txt dist/
        
        # Create a simple index.html for GitHub Pages
        cat > dist/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="pt-BR">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Sistema Espetinho - Landing Page</title>
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
            <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
            <style>
                body { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); min-height: 100vh; }
                .hero { padding: 100px 0; color: white; }
                .feature-card { background: white; border-radius: 15px; padding: 30px; margin: 20px 0; box-shadow: 0 10px 30px rgba(0,0,0,0.1); }
                .btn-download { background: #4CAF50; border: none; padding: 15px 30px; font-size: 18px; }
                .btn-download:hover { background: #45a049; }
            </style>
        </head>
        <body>
            <div class="container">
                <div class="hero text-center">
                    <h1 class="display-4 mb-4">
                        <i class="fas fa-utensils me-3"></i>
                        Sistema Espetinho
                    </h1>
                    <p class="lead mb-5">Sistema completo de gerenciamento para ponto de espetinho com câmera para leitura de código de barras</p>
                    
                    <div class="row">
                        <div class="col-md-4">
                            <div class="feature-card">
                                <i class="fas fa-camera fa-3x text-primary mb-3"></i>
                                <h4>Câmera Inteligente</h4>
                                <p>Leitura de código de barras com câmera em todos os navegadores</p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="feature-card">
                                <i class="fas fa-chart-line fa-3x text-success mb-3"></i>
                                <h4>Gestão Completa</h4>
                                <p>Controle de vendas, estoque e relatórios em tempo real</p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="feature-card">
                                <i class="fas fa-mobile-alt fa-3x text-info mb-3"></i>
                                <h4>PWA Responsivo</h4>
                                <p>Funciona offline e pode ser instalado como app</p>
                            </div>
                        </div>
                    </div>
                    
                    <div class="mt-5">
                        <a href="https://github.com/seu-usuario/sistema-espetinho" class="btn btn-download btn-lg me-3">
                            <i class="fab fa-github me-2"></i>Ver no GitHub
                        </a>
                        <a href="https://github.com/seu-usuario/sistema-espetinho/archive/refs/heads/main.zip" class="btn btn-outline-light btn-lg">
                            <i class="fas fa-download me-2"></i>Baixar ZIP
                        </a>
                    </div>
                    
                    <div class="mt-4">
                        <small class="text-light">
                            <i class="fas fa-star me-1"></i>
                            Se gostou, deixe uma ⭐ no GitHub!
                        </small>
                    </div>
                </div>
            </div>
        </body>
        </html>
        EOF
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist 